# Generated by Django 5.0.7 on 2024-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default="12:00:00",
                        help_text="Укажите время привычки",
                        verbose_name="Время в формате MM-ЧЧ",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие привычки",
                        max_length=255,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Поставьте галочку, если привычка приятная",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Укажите периодичность привычки в днях",
                        verbose_name="Периодичность привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Указывается только для полезной привычки, если нет привязки к приятной",
                        max_length=255,
                        null=True,
                        verbose_name="Награда за привычку",
                    ),
                ),
                (
                    "period_time",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Укажите период времени привычки в секундах",
                        verbose_name="Период времени привычки в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Можно публиковать в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "habit_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Укажите дату начала выполнения привычки ГГ-ММ-ДД",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("action",),
            },
        ),
    ]
